spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  batch:
    initialize-schema: always
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: true

